---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: polaris2istio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: polaris2istio
  name: polaris2istio
rules:
  - apiGroups:
      - networking.istio.io
    resources:
      - serviceentries
      - service
    verbs:
      - get
      - watch
      - list
      - update
      - patch
      - create
      - delete
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: polaris2istio
  name: polaris2istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polaris2istio
subjects:
  - kind: ServiceAccount
    name: polaris2istio
    namespace: polaris
